Added option for enabling hostNetwork for pod
Twingate/helm-charts pull request #25
Opened 2023-05-14 15:43 UTC by KR-Ravindra

Pull Request:

Feature: Adds host network capabilities to pod
First Raised: Issue #24 

Changes: When helm template is baked, it checks if value `true` is supplied for `hostNetwork`; If yes then this will enable `hostNetwork`.

Benefits:
- Solved Issue #24 
- Helps on on-premise clusters with Custom DNS deployments
- On on-premise setups, this will help in connecting to external systems that are not part of kubernetes cluster (That's a lot of power 🔥 )

2023-05-16 16:15 UTC, romankor approved these changes
GTM

2023-05-16 16:15 UTC, romankor approved these changes
GTM

2023-05-16 18:20 UTC, ekampf requested changes
See comments

2023-05-16 18:21 UTC, romankor requested changes
minor version upgrade

2023-05-23 07:48 UTC, KR-Ravindra commented
Hey @ekampf / @romankor ; I had updated the chart's minor version and also added information in chart's `README.md`. Is it good enough now?

2023-05-30 15:33 UTC, ekampf approved these changes

2023-05-30 15:33 UTC, ekampf commented
@KR-Ravindra thanks!  merging...

2023-05-30 15:33 UTC, merged