Feature/add json schema support
Twingate/helm-charts pull request #32
Opened 2023-07-28 22:23 UTC by ekampf

#### What this PR does / why we need it:
Add JSON Schema file to validate input `values.yaml` values

#### Which issue this PR fixes if any
Fixes #31 

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2023-07-31 05:02 UTC, liorr requested changes
Please check my questions and comments.

2023-07-31 05:02 UTC, liorr commented on stable/connector/templates/deployment.yaml
> +              value: "https://{{ required "Network name required" .Values.connector.network }}.{{ .Values.connector.url | default "twingate.com" }}"
I didn't see a test where we test overriding the default value

2023-07-31 05:02 UTC, liorr commented on stable/connector/values.yaml
> -  logLevel: "error"
Where do we set the default for logLevel?

2023-07-31 16:27 UTC, ekampf commented on stable/connector/values.yaml
> -  logLevel: "error"
Also I modified `test/golden/default-values.yaml` to test this...  (removed it but the generated template is the same)

2023-07-31 16:37 UTC, liorr approved these changes
LGTM

2023-08-14 21:06 UTC, ekampf commented on stable/connector/README.md
> +| `resources`                             | Resource requests and limits                                                | `{}` (The value is evaluated as a template)             |
Fixed typo

2023-08-14 22:47 UTC, merged