Add ping SecurityContext
Twingate/helm-charts pull request #5
Opened 2020-12-09 22:51 UTC by shmykyta

#### What this PR does / why we need it:

#### Which issue this PR fixes if any
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2020-12-09 23:07 UTC, ekampf commented on stable/connector/README.md
> +| `securityContext.enabled`               | Enable the securityContext. See more in values file                         | `false`                                                 |
I dont think the flag should be called `securityContext.enabled`.
It should be more specific - like `enableICMPSupport`.

2020-12-09 23:07 UTC, ekampf requested changes
see comment

2020-12-10 19:20 UTC, romankor approved these changes
GTM

2020-12-10 20:30 UTC, ekampf approved these changes

2020-12-10 20:35 UTC, merged