Support for passing in an existing secret
Twingate/helm-charts pull request #8
Opened 2021-07-15 16:39 UTC by jessebye

#### What this PR does / why we need it:

We use GitOps to manage our Kubernetes clusters, so we store the Helm values in a Git repo. To avoid having the access/refresh tokens stored in plaintext in that repo, we need to provide an existing Secret to the deployment. We provision the secret using an operator that takes a GPG-encrypted YAML file and creates a K8S secret from it.

This is pretty common practice and can be seen in other helm charts in the wild. For example, the Bitnami redis chart: https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml#L120

#### Which issue this PR fixes if any
n/a

#### Special notes for your reviewer:
n/a

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2021-07-15 18:44 UTC, romankor requested changes
Thanks for contributing ! 
All the tokens in the secrets have to be base64 encoded

2021-07-15 18:44 UTC, romankor commented on stable/connector/templates/secret.yaml
> +  TWINGATE_ACCESS_TOKEN: "{{ required "Access Token required" .Values.connector.accessToken }}"
Should be base64 encoded 
``` gotmpl
  TWINGATE_ACCESS_TOKEN: "{{ required "Access Token required" .Values.connector.accessToken | b64enc }}"
```

2021-07-15 18:44 UTC, romankor commented on stable/connector/templates/secret.yaml
> +  TWINGATE_REFRESH_TOKEN: "{{ required "Refresh Token required" .Values.connector.refreshToken }}"
also encoded

2021-07-15 18:44 UTC, romankor commented on stable/connector/README.md
> +  TWINGATE_ACCESS_TOKEN: "your access token"
```
TWINGATE_ACCESS_TOKEN: "your access token base64 encoded"
```

2021-07-15 18:44 UTC, romankor commented on stable/connector/README.md
> +  TWINGATE_REFRESH_TOKEN: "your refresh token"
same

2021-07-15 20:39 UTC, jessebye commented
@romankor good catches! I have fixed them now.

2021-07-15 23:58 UTC, romankor approved these changes
GTM

2021-07-16 00:07 UTC, jessebye commented
@romankor what is the merge process? Anything else needed from me?

2021-07-16 03:46 UTC, ekampf commented
@jessebye we'll test-run this and try to merge it tomorrow

2021-07-16 17:08 UTC, merged